export interface ReportTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  style: {
    bg: string;
    text: string;
    accent: string;
    heading: string;
    font: string;
  };
  outputType: ("summary" | "report" | "slides")[];
  promptHint: string;
  layoutGuide: string;
}

export const REPORT_TEMPLATES: ReportTemplate[] = [
  // ========== 정기회의 (6) ==========
  {
    id: "weekly_standard",
    name: "주간회의 표준",
    category: "정기회의",
    description: "액션아이템 중심 실행 요약, 진행률 대시보드",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#2563EB", heading: "#111827", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "액션아이템, 담당자, 기한을 표 형태로 정리",
    layoutGuide: "상단 요약 → 안건별 결정사항 → 액션아이템 테이블 → 다음 회의 예고",
  },
  {
    id: "weekly_dashboard",
    name: "주간 대시보드",
    category: "정기회의",
    description: "KPI + 진행률 차트 중심 보고서",
    style: { bg: "#F8FAFC", text: "#334155", accent: "#0EA5E9", heading: "#0F172A", font: "Inter" },
    outputType: ["summary", "report", "slides"],
    promptHint: "핵심 지표를 수치와 전주 대비 변화로 정리",
    layoutGuide: "KPI 카드 → 주요 성과 → 이슈/블로커 → 다음 주 목표",
  },
  {
    id: "monthly_review",
    name: "월간 리뷰",
    category: "정기회의",
    description: "월간 성과 분석 및 트렌드 요약",
    style: { bg: "#FFFFFF", text: "#1E293B", accent: "#6366F1", heading: "#0F172A", font: "Noto Sans KR" },
    outputType: ["summary", "report", "slides"],
    promptHint: "월간 성과를 부서별로 정리하고 전월 대비 분석",
    layoutGuide: "월간 요약 → 부서별 성과 → 트렌드 분석 → 다음 달 계획",
  },
  {
    id: "standup",
    name: "데일리 스탠드업",
    category: "정기회의",
    description: "어제/오늘/블로커 3줄 요약",
    style: { bg: "#18181B", text: "#E4E4E7", accent: "#22C55E", heading: "#FAFAFA", font: "JetBrains Mono" },
    outputType: ["summary"],
    promptHint: "팀원별 어제 한 일 / 오늘 할 일 / 블로커를 간결하게",
    layoutGuide: "팀원별 3줄 요약 → 공통 블로커 → 오늘 우선순위",
  },
  {
    id: "quarterly_okr",
    name: "분기 OKR 리뷰",
    category: "정기회의",
    description: "OKR 달성률 분석 및 다음 분기 목표",
    style: { bg: "#FFFBEB", text: "#78350F", accent: "#F59E0B", heading: "#451A03", font: "Pretendard" },
    outputType: ["summary", "report", "slides"],
    promptHint: "Objective별 Key Result 달성률을 점수화하고 회고",
    layoutGuide: "OKR 스코어카드 → 달성/미달성 분석 → 학습 사항 → 다음 분기 OKR 초안",
  },
  {
    id: "all_hands",
    name: "전사 미팅",
    category: "정기회의",
    description: "CEO 발표, 부서 업데이트 종합 요약",
    style: { bg: "#0F172A", text: "#CBD5E1", accent: "#818CF8", heading: "#F1F5F9", font: "Inter" },
    outputType: ["summary", "report", "slides"],
    promptHint: "경영진 메시지, 부서별 하이라이트, Q&A 핵심을 정리",
    layoutGuide: "CEO 메시지 → 부서별 하이라이트 → 공지사항 → Q&A 요약",
  },

  // ========== 전략/의사결정 (6) ==========
  {
    id: "executive_briefing",
    name: "임원 브리핑",
    category: "전략/의사결정",
    description: "1페이지 핵심 요약, C-레벨 보고용",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#1E40AF", heading: "#111827", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "핵심 결론을 먼저, 근거는 요약하여 1페이지 내",
    layoutGuide: "결론 → 핵심 근거 3개 → 리스크 → 요청 사항",
  },
  {
    id: "strategy_review",
    name: "전략 리뷰",
    category: "전략/의사결정",
    description: "전략적 의사결정 과정 문서화",
    style: { bg: "#F8FAFC", text: "#0F172A", accent: "#7C3AED", heading: "#1E1B4B", font: "Pretendard" },
    outputType: ["summary", "report", "slides"],
    promptHint: "논의된 옵션들, 각 옵션의 장단점, 최종 결정과 근거",
    layoutGuide: "배경 → 옵션 비교 → 결정 사항 → 실행 계획 → 리스크 완화",
  },
  {
    id: "board_meeting",
    name: "이사회 회의록",
    category: "전략/의사결정",
    description: "공식 의결 사항 및 경영 보고 기록",
    style: { bg: "#FFFFFF", text: "#1C1917", accent: "#B91C1C", heading: "#0C0A09", font: "Noto Serif KR" },
    outputType: ["summary", "report"],
    promptHint: "안건별 보고 내용, 질의응답, 의결 결과를 공식 형식으로",
    layoutGuide: "출석 → 전회 의사록 확인 → 안건별(보고/질의/의결) → 기타 → 폐회",
  },
  {
    id: "risk_assessment",
    name: "리스크 평가",
    category: "전략/의사결정",
    description: "리스크 식별, 영향도, 대응 전략 정리",
    style: { bg: "#FEF2F2", text: "#991B1B", accent: "#DC2626", heading: "#450A0A", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "리스크를 심각도/발생확률로 분류하고 대응 방안 포함",
    layoutGuide: "리스크 매트릭스 → 상위 5개 리스크 상세 → 대응 전략 → 모니터링 계획",
  },
  {
    id: "budget_review",
    name: "예산 심의",
    category: "전략/의사결정",
    description: "예산 배분 논의 및 승인 사항",
    style: { bg: "#F0FDF4", text: "#14532D", accent: "#16A34A", heading: "#052E16", font: "Roboto" },
    outputType: ["summary", "report"],
    promptHint: "항목별 예산 요청, 조정 내역, 최종 승인 금액 정리",
    layoutGuide: "총 예산 개요 → 부서별 요청 vs 조정 → 의결 사항 → 집행 일정",
  },
  {
    id: "investment_review",
    name: "투자 심의",
    category: "전략/의사결정",
    description: "투자 검토 보고서, IR 미팅 정리",
    style: { bg: "#0D1B2A", text: "#E0E1DD", accent: "#00B4D8", heading: "#FFFFFF", font: "Montserrat" },
    outputType: ["summary", "report", "slides"],
    promptHint: "투자 대상 개요, 시장 분석, 리턴 전망, 리스크를 구조화",
    layoutGuide: "딜 개요 → 시장/경쟁 → 재무 전망 → 리스크 → 투자 조건 → 결론",
  },

  // ========== 외부/협력 (6) ==========
  {
    id: "client_meeting",
    name: "고객 미팅",
    category: "외부/협력",
    description: "고객 요구사항, 합의사항, 후속 조치",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#0EA5E9", heading: "#0C4A6E", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "고객 요구, 합의사항, 미해결 이슈, 후속 조치를 명확히",
    layoutGuide: "미팅 개요 → 고객 요구사항 → 합의 내용 → 미해결 이슈 → 다음 스텝",
  },
  {
    id: "partnership",
    name: "파트너십 협의",
    category: "외부/협력",
    description: "파트너 협력 조건 및 MOU 내용 정리",
    style: { bg: "#F5F3FF", text: "#4C1D95", accent: "#7C3AED", heading: "#2E1065", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "협력 범위, 역할 분담, 일정, 조건을 계약서 스타일로",
    layoutGuide: "협력 배경 → 범위/역할 → 주요 조건 → 일정 → 후속 조치",
  },
  {
    id: "vendor_review",
    name: "벤더 리뷰",
    category: "외부/협력",
    description: "외주/벤더 평가 및 개선 사항",
    style: { bg: "#FFF7ED", text: "#7C2D12", accent: "#EA580C", heading: "#431407", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "벤더 성과 평가, 이슈, 개선 요청사항을 체계적으로",
    layoutGuide: "벤더 개요 → 성과 지표 → 이슈 사항 → 개선 요청 → SLA 확인",
  },
  {
    id: "negotiation",
    name: "협상 기록",
    category: "외부/협력",
    description: "협상 과정, 양보 사항, 잠정 합의 기록",
    style: { bg: "#1E293B", text: "#E2E8F0", accent: "#FBBF24", heading: "#F8FAFC", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "양측 입장, 논쟁점, 양보/합의 사항, 남은 쟁점 정리",
    layoutGuide: "참석자 → 핵심 쟁점 → 양측 입장 → 합의 내용 → 미해결 → 다음 라운드",
  },
  {
    id: "sales_meeting",
    name: "영업 미팅",
    category: "외부/협력",
    description: "영업 기회, 고객 반응, 파이프라인 관리",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#10B981", heading: "#064E3B", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "고객 니즈, 제안 내용, 반응, 성사 확률, 후속 액션",
    layoutGuide: "고객 정보 → 니즈 파악 → 제안/데모 → 고객 반응 → 후속 → 딜 스테이지",
  },
  {
    id: "government_report",
    name: "관공서 보고",
    category: "외부/협력",
    description: "공식 보고서, 정부 기관 미팅 기록",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#4338CA", heading: "#000000", font: "Noto Serif KR" },
    outputType: ["summary", "report"],
    promptHint: "공식 형식: 보고일, 참석자, 안건, 주요 내용, 조치 사항",
    layoutGuide: "보고 개요 → 안건별 논의 → 지시/조치사항 → 향후 일정",
  },

  // ========== 기술/개발 (6) ==========
  {
    id: "sprint_retro",
    name: "스프린트 회고",
    category: "기술/개발",
    description: "Good/Bad/Try 구조 회고록",
    style: { bg: "#18181B", text: "#D4D4D8", accent: "#A855F7", heading: "#FAFAFA", font: "JetBrains Mono" },
    outputType: ["summary", "report"],
    promptHint: "Good (유지), Bad (개선), Try (시도) 분류로 정리",
    layoutGuide: "스프린트 목표 달성률 → Good → Bad → Try → 다음 스프린트 개선 계획",
  },
  {
    id: "tech_review",
    name: "기술 리뷰",
    category: "기술/개발",
    description: "아키텍처, 기술 선택, 코드 리뷰 논의",
    style: { bg: "#0F172A", text: "#E2E8F0", accent: "#38BDF8", heading: "#F0F9FF", font: "Fira Code" },
    outputType: ["summary", "report", "slides"],
    promptHint: "기술 논의 사항, 결정, 근거, 트레이드오프를 명확히",
    layoutGuide: "문제 정의 → 옵션 비교 → 기술 결정 → 트레이드오프 → 구현 계획",
  },
  {
    id: "incident_postmortem",
    name: "장애 포스트모템",
    category: "기술/개발",
    description: "장애 원인 분석, 타임라인, 재발 방지",
    style: { bg: "#FEF2F2", text: "#7F1D1D", accent: "#EF4444", heading: "#450A0A", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "타임라인, 근본 원인, 영향 범위, 조치 사항, 재발 방지책",
    layoutGuide: "요약 → 타임라인 → 근본 원인 → 영향 범위 → 조치 → 재발 방지 → 후속 액션",
  },
  {
    id: "product_planning",
    name: "제품 기획",
    category: "기술/개발",
    description: "기능 기획, PRD, 로드맵 논의 정리",
    style: { bg: "#FFFFFF", text: "#1E293B", accent: "#6366F1", heading: "#312E81", font: "Pretendard" },
    outputType: ["summary", "report", "slides"],
    promptHint: "기능 요구사항, 우선순위, 일정, 리소스를 PRD 형식으로",
    layoutGuide: "배경 → 사용자 스토리 → 기능 명세 → 우선순위 → 일정 → 성공 지표",
  },
  {
    id: "design_review",
    name: "디자인 리뷰",
    category: "기술/개발",
    description: "UI/UX 피드백, 디자인 의사결정 기록",
    style: { bg: "#FAF5FF", text: "#581C87", accent: "#A855F7", heading: "#3B0764", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "디자인 안건별 피드백, 수정 방향, 최종 결정 정리",
    layoutGuide: "디자인 컨셉 → 화면별 피드백 → 수정 사항 → 결정 → 다음 이터레이션",
  },
  {
    id: "security_review",
    name: "보안 리뷰",
    category: "기술/개발",
    description: "보안 취약점 논의, 점검 결과 보고",
    style: { bg: "#0C0A09", text: "#D6D3D1", accent: "#F97316", heading: "#FAFAF9", font: "Roboto Mono" },
    outputType: ["summary", "report"],
    promptHint: "취약점, 심각도, 조치 현황, 잔여 리스크를 매트릭스로",
    layoutGuide: "점검 개요 → 발견 취약점 목록 → 심각도별 분류 → 조치 계획 → 일정",
  },

  // ========== 강연/세미나 (5) ==========
  {
    id: "keynote_summary",
    name: "키노트 요약",
    category: "강연/세미나",
    description: "강연 핵심 인사이트, 슬라이드 형태 정리",
    style: { bg: "#111827", text: "#F3F4F6", accent: "#6366F1", heading: "#FFFFFF", font: "Inter" },
    outputType: ["summary", "slides"],
    promptHint: "핵심 메시지, 주요 인사이트, 인용구를 슬라이드용으로",
    layoutGuide: "연사 소개 → 핵심 메시지 3개 → 인사이트별 상세 → 핵심 인용 → 시사점",
  },
  {
    id: "workshop",
    name: "워크샵 기록",
    category: "강연/세미나",
    description: "실습 내용, 그룹 활동, 학습 결과 정리",
    style: { bg: "#ECFDF5", text: "#064E3B", accent: "#10B981", heading: "#022C22", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "세션별 활동 내용, 그룹별 산출물, 학습 포인트 정리",
    layoutGuide: "워크샵 개요 → 세션별 기록 → 그룹 산출물 → 학습 결과 → 적용 계획",
  },
  {
    id: "conference_notes",
    name: "컨퍼런스 노트",
    category: "강연/세미나",
    description: "다수 세션 핵심 정리, 트렌드 분석",
    style: { bg: "#F8FAFC", text: "#0F172A", accent: "#0EA5E9", heading: "#082F49", font: "Pretendard" },
    outputType: ["summary", "report", "slides"],
    promptHint: "세션별 핵심 3줄 요약, 전체 트렌드, 우리에게 시사점",
    layoutGuide: "컨퍼런스 개요 → 세션별 요약 → 트렌드 키워드 → 시사점 → 적용 방안",
  },
  {
    id: "training_record",
    name: "교육/연수",
    category: "강연/세미나",
    description: "교육 내용 정리, 학습 포인트, 평가",
    style: { bg: "#FEF3C7", text: "#78350F", accent: "#D97706", heading: "#451A03", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "교육 목표, 주요 내용, 핵심 학습, 실무 적용 방안",
    layoutGuide: "교육 개요 → 커리큘럼 → 핵심 내용 → 학습 포인트 → 실무 적용 계획",
  },
  {
    id: "panel_discussion",
    name: "패널 토론",
    category: "강연/세미나",
    description: "패널별 의견, 쟁점, 결론 정리",
    style: { bg: "#1E1B4B", text: "#E0E7FF", accent: "#A5B4FC", heading: "#FFFFFF", font: "Playfair Display" },
    outputType: ["summary", "report"],
    promptHint: "패널별 주요 주장, 쟁점별 의견 대비, 공통 결론",
    layoutGuide: "주제 → 패널 소개 → 쟁점별 의견 비교 → 합의/이견 → Q&A → 시사점",
  },

  // ========== 브레인스토밍 (4) ==========
  {
    id: "brainstorm_standard",
    name: "브레인스토밍",
    category: "브레인스토밍",
    description: "아이디어 발산, 카테고리 분류, 투표 결과",
    style: { bg: "#FDF2F8", text: "#831843", accent: "#EC4899", heading: "#500724", font: "Jua" },
    outputType: ["summary", "report"],
    promptHint: "아이디어를 주제별로 분류하고, 핵심 아이디어 Top 5 선정",
    layoutGuide: "주제 → 아이디어 목록 (카테고리별) → Top 5 → 실현 가능성 평가 → 다음 스텝",
  },
  {
    id: "design_thinking",
    name: "디자인 씽킹",
    category: "브레인스토밍",
    description: "공감-정의-발상-프로토타입-테스트 단계별 기록",
    style: { bg: "#FFFFFF", text: "#374151", accent: "#8B5CF6", heading: "#1F2937", font: "Inter" },
    outputType: ["summary", "report", "slides"],
    promptHint: "디자인 씽킹 5단계별 산출물을 구조화하여 정리",
    layoutGuide: "공감 맵 → 문제 정의 → 아이디어 → 프로토타입 계획 → 테스트 계획",
  },
  {
    id: "problem_solving",
    name: "문제 해결 회의",
    category: "브레인스토밍",
    description: "5 Why, 피시본 등 구조화된 문제 분석",
    style: { bg: "#FEF9C3", text: "#713F12", accent: "#CA8A04", heading: "#422006", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "문제 정의, 근본 원인 분석, 해결 방안, 우선순위",
    layoutGuide: "문제 정의 → 현상 분석 → 근본 원인 → 해결 방안 → 우선순위 → 실행 계획",
  },
  {
    id: "innovation_lab",
    name: "이노베이션 랩",
    category: "브레인스토밍",
    description: "신규 사업/서비스 아이디어 탐색",
    style: { bg: "#0F0F0F", text: "#E5E5E5", accent: "#00FF88", heading: "#FFFFFF", font: "Space Grotesk" },
    outputType: ["summary", "report", "slides"],
    promptHint: "신규 아이디어, 시장 기회, 실현 가능성, MVP 범위 정의",
    layoutGuide: "기회 영역 → 아이디어 목록 → 평가 기준 → Top 3 상세 → MVP 정의 → 타임라인",
  },

  // ========== 내부 보고 (5) ==========
  {
    id: "team_report",
    name: "팀 보고서",
    category: "내부 보고",
    description: "팀 단위 업무 보고, 성과 정리",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#2563EB", heading: "#111827", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "팀 업무 현황, 주요 성과, 이슈, 다음 주 계획",
    layoutGuide: "팀 현황 요약 → 주요 성과 → 진행 중 업무 → 이슈/건의 → 다음 주 계획",
  },
  {
    id: "dept_briefing",
    name: "부서 브리핑",
    category: "내부 보고",
    description: "부서 간 공유용 업무 브리핑",
    style: { bg: "#F8FAFC", text: "#334155", accent: "#0EA5E9", heading: "#0F172A", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "부서 핵심 업무, 타 부서 협조 사항, 공유 필요 이슈",
    layoutGuide: "부서 현황 → 핵심 업무 진행 → 협조 요청 → 공유 사항 → 일정",
  },
  {
    id: "weekly_report",
    name: "주간 업무 보고",
    category: "내부 보고",
    description: "상급자 보고용 주간 업무 정리",
    style: { bg: "#FFFFFF", text: "#1E293B", accent: "#6366F1", heading: "#0F172A", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "금주 실적, 차주 계획, 이슈/건의사항을 간결하게",
    layoutGuide: "금주 실적 → 차주 계획 → 이슈 사항 → 건의/요청 사항",
  },
  {
    id: "progress_report",
    name: "업무 진행 보고",
    category: "내부 보고",
    description: "특정 업무/과제 진행 상황 보고",
    style: { bg: "#F0F9FF", text: "#0C4A6E", accent: "#0284C7", heading: "#082F49", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "과제 현황, 완료율, 잔여 작업, 리스크, 일정 전망",
    layoutGuide: "과제 개요 → 진행 현황 → 완료/잔여 → 리스크 → 예상 완료일",
  },
  {
    id: "meeting_minutes",
    name: "회의록 정리",
    category: "내부 보고",
    description: "내부 회의 결과 정리 및 공유",
    style: { bg: "#FAFAF9", text: "#1C1917", accent: "#78716C", heading: "#0C0A09", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "회의 목적, 논의 내용, 결정사항, 후속 조치를 간결하게",
    layoutGuide: "회의 개요 → 논의 사항 → 결정 사항 → 조치 사항(담당/기한) → 다음 회의",
  },

  // ========== 임원 보고 (5) ==========
  {
    id: "ceo_briefing",
    name: "CEO 브리핑",
    category: "임원 보고",
    description: "최고경영자 보고용, 1페이지 핵심 요약",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#1E40AF", heading: "#111827", font: "Noto Serif KR" },
    outputType: ["summary", "report", "slides"],
    promptHint: "핵심 결론 먼저, 근거 3개, 리스크, 요청사항을 1페이지로",
    layoutGuide: "핵심 결론 → 근거 3개 → 사업 임팩트 → 리스크 → 의사결정 요청",
  },
  {
    id: "executive_summary",
    name: "경영진 요약 보고",
    category: "임원 보고",
    description: "경영진 대상 사업/전략 브리핑",
    style: { bg: "#0F172A", text: "#CBD5E1", accent: "#818CF8", heading: "#F1F5F9", font: "Inter" },
    outputType: ["summary", "report", "slides"],
    promptHint: "수치 중심 현황, 핵심 이슈, 의사결정 필요 사항",
    layoutGuide: "핵심 수치 → 성과 vs 목표 → 주요 이슈 → 의사결정 사항 → 로드맵",
  },
  {
    id: "board_report",
    name: "이사회 보고",
    category: "임원 보고",
    description: "이사회 안건 보고 및 의결 사항 정리",
    style: { bg: "#FFFFFF", text: "#1C1917", accent: "#B91C1C", heading: "#0C0A09", font: "Noto Serif KR" },
    outputType: ["summary", "report"],
    promptHint: "안건별 보고, 질의응답, 의결 결과를 공식 형식으로",
    layoutGuide: "안건 개요 → 보고 내용 → 질의응답 → 의결 결과 → 후속 조치",
  },
  {
    id: "monthly_executive",
    name: "월간 경영 보고",
    category: "임원 보고",
    description: "월간 경영 성과 및 전략 이슈 보고",
    style: { bg: "#F8FAFC", text: "#0F172A", accent: "#7C3AED", heading: "#1E1B4B", font: "Pretendard" },
    outputType: ["summary", "report", "slides"],
    promptHint: "월간 KPI, 매출/비용, 핵심 이슈, 전략 방향",
    layoutGuide: "KPI 대시보드 → 재무 현황 → 사업부별 성과 → 전략 이슈 → 다음 달 중점",
  },
  {
    id: "ir_report",
    name: "IR/투자자 보고",
    category: "임원 보고",
    description: "투자자/주주 대상 사업 현황 보고",
    style: { bg: "#0D1B2A", text: "#E0E1DD", accent: "#00B4D8", heading: "#FFFFFF", font: "Montserrat" },
    outputType: ["summary", "report", "slides"],
    promptHint: "사업 성과, 시장 현황, 재무 지표, 향후 전망",
    layoutGuide: "사업 하이라이트 → 재무 실적 → 시장 현황 → 성장 전략 → 향후 전망",
  },

  // ========== 지시사항 정리 (5) ==========
  {
    id: "action_items",
    name: "액션아이템 정리",
    category: "지시사항 정리",
    description: "지시/전달사항을 담당자·기한별로 정리",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#DC2626", heading: "#111827", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "지시사항별 담당자, 기한, 완료 기준을 테이블로 정리",
    layoutGuide: "지시 배경 → 지시사항 목록(우선순위) → 담당/기한 → 유의사항",
  },
  {
    id: "task_delegation",
    name: "업무 배분표",
    category: "지시사항 정리",
    description: "팀원별 업무 배분 및 역할 정리",
    style: { bg: "#F0FDF4", text: "#14532D", accent: "#16A34A", heading: "#052E16", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "팀원별 담당 업무, 역할, 기한, 협업 사항",
    layoutGuide: "전체 목표 → 팀원별 업무 배분 → 일정 → 협업 포인트 → 보고 체계",
  },
  {
    id: "decision_directive",
    name: "의사결정 전달",
    category: "지시사항 정리",
    description: "결정사항과 후속 지시를 명확하게 전달",
    style: { bg: "#FEF2F2", text: "#991B1B", accent: "#EF4444", heading: "#450A0A", font: "Noto Sans KR" },
    outputType: ["summary", "report"],
    promptHint: "결정 배경, 결정 내용, 실행 지시, 보고 기한",
    layoutGuide: "결정 배경 → 결정 사항 → 실행 지시(담당/기한) → 보고 체계 → 유의사항",
  },
  {
    id: "followup_tracker",
    name: "후속 조치 추적",
    category: "지시사항 정리",
    description: "이전 회의 지시사항 이행 현황 점검",
    style: { bg: "#FFFBEB", text: "#78350F", accent: "#F59E0B", heading: "#451A03", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "지시사항별 이행 현황, 완료/미완료, 사유, 재지시 사항",
    layoutGuide: "점검 개요 → 이행 현황 테이블 → 미이행 사유 → 재지시/추가 지시",
  },
  {
    id: "policy_notice",
    name: "정책/지침 전달",
    category: "지시사항 정리",
    description: "새로운 정책, 규정, 가이드라인 전달",
    style: { bg: "#F5F3FF", text: "#4C1D95", accent: "#7C3AED", heading: "#2E1065", font: "Noto Serif KR" },
    outputType: ["summary", "report"],
    promptHint: "정책 배경, 주요 변경사항, 적용 범위, 시행일, FAQ",
    layoutGuide: "정책 배경 → 주요 내용 → 변경 전후 비교 → 적용 대상/일정 → FAQ",
  },

  // ========== 프로젝트 관리 (5) ==========
  {
    id: "kickoff",
    name: "프로젝트 킥오프",
    category: "프로젝트 관리",
    description: "프로젝트 시작, 목표/범위/일정 합의",
    style: { bg: "#FFFFFF", text: "#1F2937", accent: "#059669", heading: "#064E3B", font: "Pretendard" },
    outputType: ["summary", "report", "slides"],
    promptHint: "프로젝트 목표, 범위, 마일스톤, 역할, 리스크를 정의",
    layoutGuide: "프로젝트 개요 → 목표/성공 기준 → 범위 → 마일스톤 → 역할 → 리스크 → 커뮤니케이션 계획",
  },
  {
    id: "milestone_review",
    name: "마일스톤 리뷰",
    category: "프로젝트 관리",
    description: "마일스톤 달성 여부, 진행 상황 점검",
    style: { bg: "#F0FDF4", text: "#166534", accent: "#22C55E", heading: "#052E16", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "마일스톤별 완료 항목, 지연 항목, 리스크, 일정 조정",
    layoutGuide: "마일스톤 개요 → 완료/진행/지연 → 리스크 → 일정 조정 → 다음 마일스톤",
  },
  {
    id: "stakeholder_update",
    name: "이해관계자 업데이트",
    category: "프로젝트 관리",
    description: "프로젝트 상태 보고, 경영진 대상",
    style: { bg: "#1E293B", text: "#CBD5E1", accent: "#3B82F6", heading: "#F1F5F9", font: "Noto Sans KR" },
    outputType: ["summary", "report", "slides"],
    promptHint: "진행률, 핵심 이슈, 예산 현황, 의사결정 요청 사항",
    layoutGuide: "프로젝트 상태 요약 → 주요 진전 → 이슈/리스크 → 예산 → 의사결정 요청",
  },
  {
    id: "lessons_learned",
    name: "교훈 공유",
    category: "프로젝트 관리",
    description: "프로젝트 완료 후 교훈 및 개선점 정리",
    style: { bg: "#FFFBEB", text: "#92400E", accent: "#F59E0B", heading: "#78350F", font: "Pretendard" },
    outputType: ["summary", "report"],
    promptHint: "잘한 점, 개선점, 다음 프로젝트에 적용할 교훈",
    layoutGuide: "프로젝트 요약 → 성공 요인 → 개선 영역 → 핵심 교훈 → 권장사항",
  },
  {
    id: "change_request",
    name: "변경 요청",
    category: "프로젝트 관리",
    description: "스코프/일정/예산 변경 요청 및 승인 기록",
    style: { bg: "#FFF1F2", text: "#9F1239", accent: "#F43F5E", heading: "#4C0519", font: "Inter" },
    outputType: ["summary", "report"],
    promptHint: "변경 내용, 영향 분석, 비용, 승인/거절 사유",
    layoutGuide: "변경 요청 개요 → 현재 vs 변경 → 영향 분석 → 비용 → 결정 → 실행 계획",
  },
];
